ALTER TABLE events
    ADD COLUMN IF NOT EXISTS event_time TIME NULL AFTER event_date,
    ADD COLUMN IF NOT EXISTS location VARCHAR(255) NULL AFTER event_time,
    ADD COLUMN IF NOT EXISTS meeting_point VARCHAR(255) NULL AFTER location,
    ADD COLUMN IF NOT EXISTS requirements VARCHAR(1000) NULL AFTER meeting_point;

ALTER TABLE event_participants
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(200) NULL AFTER person_id,
    ADD COLUMN IF NOT EXISTS email VARCHAR(254) NULL AFTER full_name,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(50) NULL AFTER email,
    ADD COLUMN IF NOT EXISTS gender_other VARCHAR(100) NULL AFTER gender,
    ADD COLUMN IF NOT EXISTS category VARCHAR(100) NULL AFTER gender_other,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(40) NULL AFTER category,
    ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL AFTER phone;
