import { Component, input, output } from '@angular/core';
import { LucideX } from '@lucide/angular';

@Component({ selector: 'pana-step-dialog', standalone: true, imports: [LucideX],
  template: `<div class="dialog-scrim" (click)="close.emit()"><section class="dialog" [class.wide]="wide()" role="dialog" aria-modal="true" (click)="$event.stopPropagation()">
    <header><div><h2>{{ title() }}</h2><p>Paso {{ step() + 1 }} de {{ steps().length }} &#183; {{ steps()[step()] }}</p></div><button class="icon-button" type="button" aria-label="Cerrar" (click)="close.emit()"><svg lucideX [size]="20"></svg></button></header>
    <nav class="dialog-steps" aria-label="Progreso del formulario"><div class="dialog-stepper" role="list">@for (stepName of steps(); track stepName; let index = $index) {<span class="dialog-step-item" [class.active]="index === step()" [class.completed]="index < step()" role="listitem"><span class="dialog-step-dot">{{ index + 1 }}</span><span class="dialog-step-name">{{ stepName }}</span></span>@if (index < steps().length - 1) {<i class="dialog-step-line" [class.completed]="index < step()"></i>}}</div></nav>
    <div class="dialog-body"><ng-content /></div><footer><button type="button" class="secondary" [disabled]="step() === 0" (click)="previous.emit()">Anterior</button>@if (step() < steps().length - 1) {<button type="button" class="primary" [disabled]="!canContinue()" (click)="next.emit()">Continuar</button>} @else {<button type="button" class="primary" [disabled]="saving() || !canSave()" (click)="save.emit()">{{ saving() ? 'Guardando...' : 'Guardar' }}</button>}</footer>
  </section></div>`,
  styles: [`:host{display:contents}.dialog-scrim{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:color-mix(in srgb,var(--pana-ink) 40%,transparent)}.dialog{display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;width:min(900px,100%);max-height:min(860px,94vh);border:1px solid var(--pana-outline);border-radius:var(--pana-radius-xl);background:var(--pana-surface);color:var(--pana-ink)}.dialog.wide{width:min(1200px,100%)}.dialog header,.dialog footer{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 24px}.dialog header{border-bottom:1px solid var(--pana-navbar-outline)}.dialog h2,.dialog p{margin:0}.dialog h2{font-size:1.35rem}.dialog p{margin-top:4px;color:var(--pana-muted);font-size:.9rem}.icon-button{width:40px;min-height:40px;padding:0;border:0;border-radius:50%;background:transparent;color:var(--pana-muted);cursor:pointer}.dialog-steps{padding:12px 24px 10px;border-bottom:1px solid var(--pana-navbar-outline)}.dialog-stepper{display:flex;align-items:flex-start;width:100%;overflow-x:auto}.dialog-step-item{display:grid;flex:1 1 0;justify-items:center;gap:5px;min-width:100px;color:var(--pana-muted);text-align:center}.dialog-step-dot{display:grid;width:28px;height:28px;place-items:center;border:2px solid var(--pana-outline);border-radius:50%;background:var(--pana-surface);color:var(--pana-muted);font-size:.75rem;font-weight:600}.dialog-step-item.active .dialog-step-dot{border-color:var(--pana-purple);background:var(--pana-purple);color:#fff}.dialog-step-item.completed .dialog-step-dot{border-color:var(--pana-purple);background:var(--pana-purple-soft);color:var(--pana-purple)}.dialog-step-name{font-size:.72rem;line-height:1.2}.dialog-step-item.active .dialog-step-name,.dialog-step-item.completed .dialog-step-name{color:var(--pana-purple);font-weight:600}.dialog-step-line{flex:1 1 20px;min-width:12px;height:2px;margin-top:13px;background:var(--pana-outline)}.dialog-step-line.completed{background:var(--pana-purple)}.dialog-body{min-height:0;overflow:auto;padding:24px}.dialog footer{border-top:1px solid var(--pana-navbar-outline)}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:42px;padding:8px 16px;border:1px solid var(--pana-outline);border-radius:var(--pana-radius-pill);background:var(--pana-surface);color:var(--pana-purple);font:inherit;cursor:pointer}.primary{border-color:var(--pana-purple);background:var(--pana-purple);color:#fff}.dialog button:disabled{opacity:.45;cursor:default}@media(max-width:650px){.dialog-scrim{padding:0}.dialog{width:100%;max-height:100vh;border-radius:0}.dialog header,.dialog-steps,.dialog-body,.dialog footer{padding-inline:16px}.dialog-step-item{min-width:88px}}`],
})
export class StepDialogComponent {
  readonly title = input.required<string>(); readonly wide = input(false); readonly steps = input.required<string[]>(); readonly step = input(0); readonly saving = input(false); readonly canContinue = input(true); readonly canSave = input(true);
  readonly close = output<void>(); readonly previous = output<void>(); readonly next = output<void>(); readonly save = output<void>();
}
