export type EcuadorProvince = { name: string; cities: string[] };

export const ECUADOR_LOCATIONS: EcuadorProvince[] = [
  { name: 'Azuay', cities: ['Cuenca', 'Girón', 'Gualaceo', 'Paute', 'Santa Isabel', 'Sigsig'] },
  { name: 'Bolívar', cities: ['Guaranda', 'Caluma', 'Chillanes', 'Chimbo', 'Echeandía', 'Las Naves', 'San Miguel'] },
  { name: 'Cañar', cities: ['Azogues', 'Biblián', 'Cañar', 'Déleg', 'El Tambo', 'La Troncal', 'Suscal'] },
  { name: 'Carchi', cities: ['Tulcán', 'Bolívar', 'Espejo', 'Mira', 'Montúfar', 'San Pedro de Huaca'] },
  { name: 'Chimborazo', cities: ['Riobamba', 'Alausí', 'Colta', 'Chambo', 'Chunchi', 'Guamote', 'Guano', 'Pallatanga', 'Penipe'] },
  { name: 'Cotopaxi', cities: ['Latacunga', 'La Maná', 'Pangua', 'Pujilí', 'Salcedo', 'Saquisilí', 'Sigchos'] },
  { name: 'El Oro', cities: ['Machala', 'Arenillas', 'Atahualpa', 'Balsas', 'Chilla', 'El Guabo', 'Huaquillas', 'Las Lajas', 'Marcabelí', 'Pasaje', 'Piñas', 'Portovelo', 'Santa Rosa', 'Zaruma'] },
  { name: 'Esmeraldas', cities: ['Esmeraldas', 'Atacames', 'Eloy Alfaro', 'Muisne', 'Quinindé', 'Rioverde', 'San Lorenzo'] },
  { name: 'Galápagos', cities: ['Puerto Baquerizo Moreno', 'Puerto Ayora', 'Puerto Villamil'] },
  { name: 'Guayas', cities: ['Guayaquil', 'Alfredo Baquerizo Moreno', 'Balao', 'Balzar', 'Colimes', 'Daule', 'Durán', 'El Empalme', 'El Triunfo', 'General Antonio Elizalde', 'Isidro Ayora', 'Lomas de Sargentillo', 'Milagro', 'Naranjal', 'Naranjito', 'Nobol', 'Palestina', 'Pedro Carbo', 'Playas', 'Salitre', 'Samborondón', 'Santa Lucía', 'Simón Bolívar', 'Yaguachi'] },
  { name: 'Imbabura', cities: ['Ibarra', 'Antonio Ante', 'Cotacachi', 'Otavalo', 'Pimampiro', 'Urcuquí'] },
  { name: 'Loja', cities: ['Loja', 'Calvas', 'Catamayo', 'Celica', 'Chaguarpamba', 'Espíndola', 'Gonzanamá', 'Macará', 'Olmedo', 'Paltas', 'Pindal', 'Puyango', 'Quilanga', 'Saraguro', 'Sozoranga', 'Zapotillo'] },
  { name: 'Los Ríos', cities: ['Babahoyo', 'Baba', 'Buena Fe', 'Mocache', 'Montalvo', 'Palenque', 'Puebloviejo', 'Quevedo', 'Quinsaloma', 'Urdaneta', 'Valencia', 'Ventanas', 'Vinces'] },
  { name: 'Manabí', cities: ['Portoviejo', '24 de Mayo', 'Bolívar', 'Chone', 'El Carmen', 'Flavio Alfaro', 'Jama', 'Jaramijó', 'Jipijapa', 'Junín', 'Manta', 'Montecristi', 'Olmedo', 'Paján', 'Pedernales', 'Pichincha', 'Puerto López', 'Rocafuerte', 'San Vicente', 'Santa Ana', 'Sucre', 'Tosagua'] },
  { name: 'Morona Santiago', cities: ['Macas', 'Gualaquiza', 'Huamboya', 'Limón Indanza', 'Logroño', 'Palora', 'Pablo Sexto', 'San Juan Bosco', 'Santiago', 'Sucúa', 'Taisha', 'Tiwintza'] },
  { name: 'Napo', cities: ['Tena', 'Archidona', 'Carlos Julio Arosemena Tola', 'El Chaco', 'Quijos'] },
  { name: 'Orellana', cities: ['Francisco de Orellana', 'Aguarico', 'La Joya de los Sachas', 'Loreto'] },
  { name: 'Pastaza', cities: ['Puyo', 'Arajuno', 'Mera', 'Santa Clara'] },
  { name: 'Pichincha', cities: ['Quito', 'Cayambe', 'Mejía', 'Pedro Moncayo', 'Pedro Vicente Maldonado', 'Puerto Quito', 'Rumiñahui', 'San Miguel de los Bancos'] },
  { name: 'Santa Elena', cities: ['Santa Elena', 'La Libertad', 'Salinas'] },
  { name: 'Santo Domingo de los Tsáchilas', cities: ['Santo Domingo', 'La Concordia'] },
  { name: 'Sucumbíos', cities: ['Nueva Loja', 'Cascales', 'Cuyabeno', 'Gonzalo Pizarro', 'Putumayo', 'Shushufindi', 'Sucumbíos'] },
  { name: 'Tungurahua', cities: ['Ambato', 'Baños de Agua Santa', 'Cevallos', 'Mocha', 'Patate', 'Pelileo', 'Píllaro', 'Quero', 'Tisaleo'] },
  { name: 'Zamora Chinchipe', cities: ['Zamora', 'Centinela del Cóndor', 'Chinchipe', 'El Pangui', 'Nangaritza', 'Palanda', 'Paquisha', 'Yacuambi', 'Yantzaza'] },
];
