import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, DestroyRef, inject, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ActivatedRoute, Router } from '@angular/router';
import { LucideArrowRight, LucideBookOpen, LucideBriefcase, LucideCalendar, LucideCheckCircle2, LucideCircleHelp, LucideClipboardCheck, LucideClock, LucideCreditCard, LucideEye, LucideEyeOff, LucideGraduationCap, LucideHeartHandshake, LucideLockKeyhole, LucideMail, LucideMapPin, LucidePhone, LucideSchool, LucideSparkles, LucideUser } from '@lucide/angular';
import { RegistrationApiService, RegistrationCourse, RegistrationPayload } from './registration-api.service';

type RegistrationData = { name: string; id: string; course: string; birthDate: string; age: number | null; gender: string; phone: string; email: string; address: string; institution: string; career: string; level: string; motivation: string; skills: string; volunteer: string; volunteerDetails: string; password: string; days: string[]; schedules: string[]; terms: boolean; };

@Component({ selector: 'pana-registration', standalone: true, imports: [DatePipe, FormsModule, MatButtonModule, LucideArrowRight, LucideBookOpen, LucideBriefcase, LucideCalendar, LucideCheckCircle2, LucideCircleHelp, LucideClipboardCheck, LucideClock, LucideCreditCard, LucideEye, LucideEyeOff, LucideGraduationCap, LucideHeartHandshake, LucideLockKeyhole, LucideMail, LucideMapPin, LucidePhone, LucideSchool, LucideSparkles, LucideUser], templateUrl: './registration.component.html', styleUrl: './registration.component.scss' })
export class RegistrationComponent {
  private readonly router = inject(Router); private readonly route = inject(ActivatedRoute); private readonly api = inject(RegistrationApiService); private readonly destroyRef = inject(DestroyRef);
  private readonly draftKey = 'pana-registration-draft';
  private readonly draftVersion = 'volunteer-default-no-v1';
  readonly closed = output<void>(); readonly step = signal(0); readonly submitted = signal(false); readonly busy = signal(false); readonly passwordVisible = signal(false); readonly error = signal(''); readonly errorField = signal(''); readonly courses = signal<RegistrationCourse[]>([]); readonly coursesLoading = signal(true);
  readonly steps = ['Datos personales', 'Curso y disponibilidad', 'Información adicional', 'Documentos y confirmación']; readonly availableDays = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']; readonly availableSchedules = ['Mañana', 'Tarde'];
  readonly data: RegistrationData = { name: '', id: '', course: '', birthDate: '', age: null, gender: 'Masculino', phone: '', email: '', address: '', institution: '', career: '', level: '1', motivation: '', skills: '', volunteer: 'No', volunteerDetails: '', password: '', days: [], schedules: [], terms: false };
  readonly emailDomains = ['@gmail.com', '@outlook.com']; emailDomain = '@gmail.com';
  readonly dateYears = Array.from({ length: 80 }, (_, index) => new Date().getFullYear() - index); readonly dateMonths = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']; birthYear = ''; birthMonth = ''; birthDay = '';
  constructor() { this.restoreDraft(); const sync = (event: StorageEvent) => { if (event.key === this.draftKey) this.restoreDraft(event.newValue); }; const routeSub = this.route.paramMap.subscribe(params => { const value = Number(params.get('step')); const index = Number.isInteger(value) && value >= 1 && value <= this.steps.length ? value - 1 : 0; this.step.set(index); if (!params.get('step')) void this.router.navigate(['/inscripcion', 1], { replaceUrl: true }); }); window.addEventListener('storage', sync); this.destroyRef.onDestroy(() => { routeSub.unsubscribe(); window.removeEventListener('storage', sync); }); this.api.availableCourses().subscribe({ next: result => { this.courses.set(result.courses); if (!this.data.course) this.data.course = result.courses.find(course => course.is_available)?.name ?? ''; }, error: () => { this.error.set('No se pudieron cargar los cursos disponibles.'); this.coursesLoading.set(false); }, complete: () => this.coursesLoading.set(false) }); }
  selectedCourse(): RegistrationCourse | undefined { return this.courses().find(course => course.name === this.data.course); }
  close(): void { this.closed.emit(); void this.router.navigateByUrl('/login'); }
  updateAge(): void { if (!this.data.birthDate) { this.data.age = null; return; } const birth = new Date(`${this.data.birthDate}T00:00:00`); const today = new Date(); let age = today.getFullYear() - birth.getFullYear(); if (today < new Date(today.getFullYear(), birth.getMonth(), birth.getDate())) age--; this.data.age = age; }
  toggleValue(values: string[], value: string): void { const index = values.indexOf(value); index === -1 ? values.push(value) : values.splice(index, 1); }
  togglePassword(): void { this.passwordVisible.update(value => !value); }
  persistDraft(): void { const draft: Partial<RegistrationData> & { version?: string } = { ...this.data, version: this.draftVersion }; draft.password = undefined; localStorage.setItem(this.draftKey, JSON.stringify(draft)); }
  private restoreDraft(raw: string | null = localStorage.getItem(this.draftKey)): void { if (!raw) return; try { const draft = JSON.parse(raw) as Partial<RegistrationData> & { version?: string }; const volunteer = draft.version === this.draftVersion ? draft.volunteer : 'No'; Object.assign(this.data, draft, { password: '', volunteer }); this.data.id = this.data.id.replace(/\D/g, '').slice(0, 10); if (this.data.phone.startsWith('09')) this.data.phone = this.data.phone.slice(2); this.data.phone = this.data.phone.replace(/\D/g, '').slice(0, 8); if (this.data.birthDate) [this.birthYear, this.birthMonth, this.birthDay] = this.data.birthDate.split('-'); if (!this.data.gender) this.data.gender = 'Masculino'; if (!this.data.level) this.data.level = '1'; if (!this.data.volunteer) this.data.volunteer = 'No'; const parts = this.data.email.split('@'); if (parts.length > 1) { this.data.email = parts[0]; this.emailDomain = `@${parts[1]}`; } if (!this.emailDomains.includes(this.emailDomain)) this.emailDomain = '@gmail.com'; } catch { localStorage.removeItem(this.draftKey); } }
  dateDays(): number[] { const max = this.birthYear && this.birthMonth ? new Date(Number(this.birthYear), Number(this.birthMonth), 0).getDate() : 31; return Array.from({ length: max }, (_, index) => index + 1); }
  syncBirthDate(): void { if (!this.birthYear || !this.birthMonth || !this.birthDay) { this.data.birthDate = ''; this.data.age = null; return; } if (Number(this.birthDay) > this.dateDays().length) this.birthDay = String(this.dateDays().length); this.data.birthDate = `${this.birthYear}-${this.birthMonth.padStart(2, '0')}-${this.birthDay.padStart(2, '0')}`; this.updateAge(); }
  fullEmail(): string { return this.data.email.includes('@') ? this.data.email : `${this.data.email}${this.emailDomain}`; }
  fullPhone(): string { return `09${this.data.phone}`; }
  formatCoursePeriod(startValue: string, endValue: string): string { const start = new Date(`${startValue}T00:00:00`); const end = new Date(`${endValue}T00:00:00`); const startText = `${start.getDate()} de ${this.dateMonths[start.getMonth()].toLowerCase()}`; const endText = `${end.getDate()} de ${this.dateMonths[end.getMonth()].toLowerCase()}`; return start.getFullYear() === end.getFullYear() ? `${startText} hasta ${endText} de ${end.getFullYear()}` : `${startText} de ${start.getFullYear()} hasta ${endText} de ${end.getFullYear()}`; }
  canContinue(): boolean { if (this.step() === 0) return this.data.name.trim().split(/\s+/).length >= 2 && /^\d{10}$/.test(this.data.id) && !!this.data.birthDate && !!this.data.gender && /^[^\s@]+$/.test(this.data.email) && this.data.password.length >= 12; if (this.step() === 1) return !!this.data.course && this.data.days.length > 0 && this.data.schedules.length > 0; if (this.step() === 2) return /^\d{8}$/.test(this.data.phone) && !!this.data.address.trim() && !!this.data.institution.trim() && !!this.data.career.trim() && !!this.data.level && !!this.data.motivation.trim() && !!this.data.skills.trim() && !!this.data.volunteer && (this.data.volunteer === 'No' || !!this.data.volunteerDetails.trim()); return true; }
  private setStep(index: number): void { this.step.set(index); void this.router.navigate(['/inscripcion', index + 1], { replaceUrl: true }); }
  next(): void { this.error.set(''); this.errorField.set(''); const message = this.missingFieldMessage(); if (message) { this.error.set(message); return; } if (this.step() < this.steps.length - 1) this.setStep(this.step() + 1); }
  private missingFieldMessage(): string {
    if (this.step() === 0 && this.data.name.trim().split(/\s+/).length < 2) return this.invalid('name', 'Escribe tus nombres y apellidos completos.');
    if (this.step() === 0 && !/^\d{10}$/.test(this.data.id)) return this.invalid('id', 'La cédula debe tener exactamente 10 dígitos.');
    if (this.step() === 0 && (!this.data.email || !/^[^\s@]+$/.test(this.data.email))) return this.invalid('email', 'Ingresa la parte inicial de tu correo.');
    if (this.step() === 0) { if (!this.data.name) return this.invalid('name', 'Ingresa tus nombres y apellidos.'); if (!this.data.id) return this.invalid('id', 'Ingresa tu cédula de identidad.'); if (!this.data.birthDate) return this.invalid('birthDate', 'Selecciona tu fecha de nacimiento.'); if (!this.data.gender) return this.invalid('gender', 'Selecciona tu género.'); if (!this.data.email) return this.invalid('email', 'Ingresa tu correo electrónico.'); if (this.data.password.length < 12) return this.invalid('password', 'La contraseña debe tener al menos 12 caracteres.'); }
    if (this.step() === 1) { if (!this.data.course) return this.invalid('course', 'Selecciona un curso gratuito.'); if (!this.data.days.length) return this.invalid('days', 'Selecciona al menos un día disponible.'); if (!this.data.schedules.length) return this.invalid('schedules', 'Selecciona al menos un horario disponible.'); }
    if (this.step() === 2) { if (!/^\d{8}$/.test(this.data.phone)) return this.invalid('phone', 'Ingresa los 8 dígitos después del 09.'); if (!this.data.address) return this.invalid('address', 'Ingresa tu dirección de domicilio.'); if (!this.data.motivation) return this.invalid('motivation', 'Indica por qué deseas participar.'); if (!this.data.skills) return this.invalid('skills', 'Indica qué habilidades puedes aportar.'); if (!this.data.volunteer) return this.invalid('volunteer', 'Indica si has participado en voluntariado.'); }
    return '';
  }
  fieldError(field: string): string { return this.errorField() === field ? this.error() : ''; }
  private invalid(field: string, message: string): string { this.errorField.set(field); return message; }
  back(): void { this.error.set(''); this.setStep(Math.max(0, this.step() - 1)); }
  goTo(index: number): void { if (index <= this.step()) { this.error.set(''); this.setStep(index); } }
  submit(): void {
    if (this.busy()) return; this.updateAge(); this.errorField.set('');
    if (this.data.name.trim().split(/\s+/).length < 2) { this.errorField.set('name'); this.error.set('Escribe tus nombres y apellidos completos.'); return; }
    if ((this.data.age ?? 0) < 18 || (this.data.age ?? 0) > 29) { this.errorField.set('birthDate'); this.error.set('La inscripción está disponible para personas de 18 a 29 años.'); return; }
    if (!this.data.days.length) { this.errorField.set('days'); this.error.set('Selecciona al menos un día disponible.'); return; } if (!this.data.schedules.length) { this.errorField.set('schedules'); this.error.set('Selecciona al menos un horario disponible.'); return; } if (!this.data.terms) { this.errorField.set('terms'); this.error.set('Acepta los términos para continuar.'); return; }
    const payload: RegistrationPayload = { name: this.data.name, id: this.data.id, course: this.data.course, birthDate: this.data.birthDate, gender: this.data.gender, phone: this.fullPhone(), email: this.fullEmail(), address: this.data.address, institution: this.data.institution, career: this.data.career, level: this.data.level, motivation: this.data.motivation, skills: this.data.skills, volunteer: this.data.volunteer, volunteerDetails: this.data.volunteerDetails, password: this.data.password, days: this.data.days, schedules: this.data.schedules, terms: this.data.terms };
     this.busy.set(true); this.error.set(''); this.api.create(payload).subscribe({ next: () => { setTimeout(() => { localStorage.removeItem(this.draftKey); this.busy.set(false); this.submitted.set(true); }, 500); }, error: (failure: HttpErrorResponse) => { setTimeout(() => { this.error.set(this.messageFor(failure)); this.busy.set(false); }, 500); } });
  }
  private messageFor(failure: HttpErrorResponse): string { const code = failure.error?.error; if (failure.status === 0) return 'No se pudo conectar con el servidor. Verifica que el backend esté encendido.'; if (code === 'invalid_name') return 'Escribe tus nombres y apellidos completos.'; if (code === 'invalid_ci') return 'La cédula de identidad no tiene un formato válido.'; if (code === 'invalid_email') return 'El correo electrónico no tiene un formato válido.'; if (code === 'age_not_allowed') return 'La inscripción está disponible para personas de 18 a 29 años.'; if (code === 'course_unavailable') return 'El curso seleccionado ya no está disponible.'; if (code === 'registration_already_exists') return 'Ya existe una inscripción con esa cédula o correo electrónico.'; if (failure.status >= 500) return 'El servidor no pudo procesar la inscripción. Revisa los datos e inténtalo nuevamente.'; return 'No se pudo enviar la inscripción. Revisa los datos indicados e inténtalo de nuevo.'; }
}
